theme: jekyll-theme-slate
title: C++ For Big Numbers
description: My implementation of big number arithmetic in C++, this will let you perform computation on extreamly large numbers, like really large... beyond 18 digits.
